version: "3"

services:
    ubuntu:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ../:/root/workspace/
        runtime: nvidia
        environment:
            NVIDIA_VISIBLE_DEVICES: all
        stdin_open: true
